server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://ub20-mech:3306/article?serverTimezone=UTC&characterEncoding=utf-8
    username: ubmechdb
    password: Nta0427a@tjw
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1GB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    serialization:
      #格式化输出
      indent_output: true
      fail_on_empty_beans: false #忽略无法转换的对象
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

# database通用配置
mybatis-plus:
  global-config:
    db-config:
      #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: Y
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: N
      id-type: ASSIGN_ID
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# swagger配置
swagger:
  enable: true